---

- hosts: all
  become: true
  tasks:

  - name: Uninstall repository index
    apt: 
      update_cache: yes 

  - name: Uninstall apache2 package
    apt: 
      name: apache2
      state: absent


  - name: Uninstall php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
